#!/bin/sh
if [ -d /trace/logs ]
then
    rm -rf /trace/logs
fi
mkdir -p /trace/logs
LOGFILE="$1"
CONFIGTUPLE=$(cat $LOGFILE | grep "logs")
NODELIST=$(echo $CONFIGTUPLE | cut -d '[' -f2 | cut -d ']' -f1 | sed 's/,/ /g')
for i in $NODELIST
do
     if [ "$i" = `hostname -s` ]; then
           cp -r /var/log/tracetool/. /trace/logs/
     else
     scp -r root@$i:/var/log/tracetool/. /trace/logs/
     fi
done























