#!/bin/sh

[ $# -eq 0 ] && echo "Usage: tracetool command [ args ]"

# Get command to execute
cmd="$1"; shift
echo $cmd
echo

function call_mfa()
{
    echo "@ = $@, * = $*"
    echo "$@" | erl_call -r -h trace_enode -sname dallas0 -c DALLAS -e
    [ $? -ne 0 ] && echo 'Erlang call failed'
}

# Check command and handle command arguments
if [ "$cmd" = 'start' ]; then
    args="'$@'"
    call_mfa "tracetool:start($args)."
else
    call_mfa "tracetool:stop()."
fi

ret=$?
echo
exit $ret